import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        {/* Load PSPDFKit script using Next.js Script component */}
        <Script
          src="/nutrient-viewer-lib/nutrient-viewer.js"
          strategy="beforeInteractive" // Load before the page becomes interactive to reference window.PSPDFKit in the client
        />
      </head>
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
